// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth": {
    params: {};
  };
  "/auth/callback": {
    params: {};
  };
  "/billing": {
    params: {};
  };
  "/user": {
    params: {};
  };
  "/invite/:token": {
    params: {
      "token": string;
    };
  };
  "/org/:orgId": {
    params: {
      "orgId": string;
    };
  };
  "/org/:orgId/members": {
    params: {
      "orgId": string;
    };
  };
  "/org/:orgId/api-keys": {
    params: {
      "orgId": string;
    };
  };
  "/org/:orgId/invitations": {
    params: {
      "orgId": string;
    };
  };
  "/org/:orgId/bots": {
    params: {
      "orgId": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/auth" | "/auth/callback" | "/billing" | "/user" | "/invite/:token" | "/org/:orgId" | "/org/:orgId/members" | "/org/:orgId/api-keys" | "/org/:orgId/invitations" | "/org/:orgId/bots";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/auth.tsx": {
    id: "routes/auth";
    page: "/auth";
  };
  "routes/auth.callback.tsx": {
    id: "routes/auth.callback";
    page: "/auth/callback";
  };
  "routes/billing.tsx": {
    id: "routes/billing";
    page: "/billing";
  };
  "routes/user.tsx": {
    id: "routes/user";
    page: "/user";
  };
  "routes/invite.$token.tsx": {
    id: "routes/invite.$token";
    page: "/invite/:token";
  };
  "routes/org.$orgId.tsx": {
    id: "routes/org.$orgId";
    page: "/org/:orgId" | "/org/:orgId/members" | "/org/:orgId/api-keys" | "/org/:orgId/invitations" | "/org/:orgId/bots";
  };
  "routes/org.$orgId/_index.tsx": {
    id: "routes/org.$orgId/_index";
    page: "/org/:orgId";
  };
  "routes/org.$orgId/members.tsx": {
    id: "routes/org.$orgId/members";
    page: "/org/:orgId/members";
  };
  "routes/org.$orgId/api-keys.tsx": {
    id: "routes/org.$orgId/api-keys";
    page: "/org/:orgId/api-keys";
  };
  "routes/org.$orgId/invitations.tsx": {
    id: "routes/org.$orgId/invitations";
    page: "/org/:orgId/invitations";
  };
  "routes/org.$orgId/bots.tsx": {
    id: "routes/org.$orgId/bots";
    page: "/org/:orgId/bots";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/auth": typeof import("./app/routes/auth.tsx");
  "routes/auth.callback": typeof import("./app/routes/auth.callback.tsx");
  "routes/billing": typeof import("./app/routes/billing.tsx");
  "routes/user": typeof import("./app/routes/user.tsx");
  "routes/invite.$token": typeof import("./app/routes/invite.$token.tsx");
  "routes/org.$orgId": typeof import("./app/routes/org.$orgId.tsx");
  "routes/org.$orgId/_index": typeof import("./app/routes/org.$orgId/_index.tsx");
  "routes/org.$orgId/members": typeof import("./app/routes/org.$orgId/members.tsx");
  "routes/org.$orgId/api-keys": typeof import("./app/routes/org.$orgId/api-keys.tsx");
  "routes/org.$orgId/invitations": typeof import("./app/routes/org.$orgId/invitations.tsx");
  "routes/org.$orgId/bots": typeof import("./app/routes/org.$orgId/bots.tsx");
};