use std::{
    collections::{BTreeMap, HashMap},
    fmt::Debug,
    path::PathBuf,
};

use cargo_metadata::TargetKind;
use color_eyre::{
    Result, Section, SectionExt,
    eyre::{Context, OptionExt as _, bail, eyre},
};
use derive_more::Debug as DebugExt;
use itertools::Itertools as _;
use scopeguard::defer;
use serde::{Deserialize, Serialize};
use tap::{Pipe as _, Tap as _, TapFallible as _};
use tokio::task::spawn_blocking;
use tracing::{debug, instrument, trace};
use uuid::Uuid;

use crate::{
    cargo::{
        self, BuildPlan, BuildScriptOutput, CargoBuildArguments, CargoCompileMode, Fingerprint,
        Profile, RustcMetadata, build_plan::RustcArgument,
    },
    fs, mk_rel_dir, mk_rel_file,
    path::{AbsDirPath, AbsFilePath, JoinWith as _, TryJoinWith as _},
};

/// The Cargo workspace of a build.
///
/// Workspaces contain all the information needed to unambiguously specify the
/// files in a build. Note that workspaces are constructed with a specific
/// invocation in mind, since we parse some of its configuration fields from a
/// build invocation's arguments.
#[derive(Clone, Eq, PartialEq, Hash, DebugExt, Serialize, Deserialize)]
pub struct Workspace {
    /// The root directory of the workspace.
    pub root: AbsDirPath,

    /// The $CARGO_HOME value.
    pub cargo_home: AbsDirPath,

    /// The build profile of this workspace invocation.
    pub profile: Profile,

    /// The target triple flag of this workspace invocation, if set.
    ///
    /// ## Cross-Compilation Directory Structure
    ///
    /// When cross-compiling with `--target <triple>`, Cargo uses a complex
    /// directory structure that separates host and target artifacts:
    ///
    /// ```not_rust
    /// target/
    /// ├── <triple>/                    ← Target platform artifacts
    /// │   └── <profile>/
    /// │       ├── deps/                ← Compiled libraries (.rlib, .so, etc.)
    /// │       ├── build/               ← Build script OUTPUT directories
    /// │       │   └── pkg-hash/
    /// │       │       └── out/         ← Files generated by build scripts
    /// │       └── .fingerprint/        ← Fingerprints for:
    /// │           ├── pkg-hash1/       ← - Library compilation
    /// │           └── pkg-hash2/       ← - Build script EXECUTION
    /// └── <profile>/                   ← Host platform artifacts
    ///     ├── build/                   ← Build script BINARIES
    ///     │   └── pkg-hash/
    ///     │       └── build-script-*   ← Compiled build script executables
    ///     └── .fingerprint/            ← Fingerprints for:
    ///         └── pkg-hash/            ← - Build script COMPILATION
    /// ```
    ///
    /// ### The Confusing Part: Build Scripts
    ///
    /// Build scripts have a split personality during cross-compilation:
    ///
    /// 1. **Compilation** (host): The build script itself is a Rust program that
    ///    must run on the build machine (host). Its compiled binary and compilation
    ///    fingerprint live in `target/<profile>/` (no triple).
    ///
    /// 2. **Execution** (target): When the build script runs, it generates files
    ///    for the target platform. Its output directory and execution fingerprint
    ///    live in `target/<triple>/<profile>/`.
    ///
    /// This means for a package like `serde` with a build script:
    /// - Binary: `target/debug/build/serde-{hash1}/build-script-build`
    /// - Binary fingerprint: `target/debug/.fingerprint/serde-{hash1}/`
    /// - Output directory:
    ///   `target/aarch64-apple-darwin/debug/build/serde-{hash2}/out/`
    /// - Output fingerprint:
    ///   `target/aarch64-apple-darwin/debug/.fingerprint/serde-{hash2}/`
    ///
    /// Notice that `hash1` (compilation) and `hash2` (execution) are different
    /// because they represent different compilation units with different
    /// dependencies and flags.
    pub target_arch: Option<String>,
}

impl Workspace {
    /// Create a workspace by parsing `cargo metadata` from the given directory.
    #[instrument(name = "Workspace::from_argv_in_dir")]
    pub async fn from_argv_in_dir(
        path: &AbsDirPath,
        args: impl AsRef<CargoBuildArguments> + Debug,
    ) -> Result<Self> {
        let args = args.as_ref();

        let (workspace_root, workspace_target) = {
            // TODO: Maybe we should just replicate this logic and perform it
            // statically using filesystem operations instead of shelling out?
            // This costs something on the order of 200ms, which is not
            // _terrible_ but feels much slower than if we just did our own
            // filesystem reads, especially since we don't actually use any of
            // the logic except the paths.
            let manifest_path = args.manifest_path().map(String::from);
            let cmd_current_dir = path.as_std_path().to_path_buf();
            let metadata = spawn_blocking(move || -> Result<_> {
                cargo_metadata::MetadataCommand::new()
                    .tap_mut(|cmd| {
                        if let Some(p) = manifest_path {
                            cmd.manifest_path(p);
                        }
                    })
                    .current_dir(cmd_current_dir)
                    .exec()
                    .context("exec and parse cargo metadata")
            })
            .await
            .context("join task")?
            .tap_ok(|metadata| debug!(?metadata, "cargo metadata"))
            .context("get cargo metadata")?;
            (
                AbsDirPath::try_from(&metadata.workspace_root)
                    .context("parse workspace root as absolute directory")?,
                AbsDirPath::try_from(&metadata.target_directory)
                    .context("parse workspace target as absolute directory")?,
            )
        };

        let cargo_home = spawn_blocking({
            let workspace_root = workspace_root.clone();
            move || home::cargo_home_with_cwd(workspace_root.as_std_path())
        })
        .await
        .context("join background task")?
        .context("get $CARGO_HOME")?
        .pipe(AbsDirPath::try_from)
        .context("parse path as utf8")?;

        let profile = args.profile().map(Profile::from).unwrap_or(Profile::Debug);
        let target_arch = args.target().map(String::from);

        Ok(Self {
            root: workspace_root,
            cargo_home,
            profile,
            target_arch,
        })
    }

    /// Create a workspace from the current working directory.
    ///
    /// Convenience method that calls `from_argv_in_dir`
    /// using the current working directory as the workspace root.
    #[instrument(name = "Workspace::from_argv")]
    pub async fn from_argv(args: impl AsRef<CargoBuildArguments> + Debug) -> Result<Self> {
        let pwd = AbsDirPath::current().context("get working directory")?;
        Self::from_argv_in_dir(&pwd, args).await
    }

    /// Get the build directory for this workspace. Note that we use the "build
    /// dir" terminology from Cargo's upcoming split between final and
    /// intermediate build artifacts[^1].
    ///
    /// [^1]: https://github.com/rust-lang/cargo/issues/6790
    #[instrument(name = "Workspace::build_dir")]
    pub fn build_dir(&self) -> AbsDirPath {
        // TODO: Support all sorts of configuration flags and environment
        // variables that can modify this directory's location.
        self.root.join(mk_rel_dir!("target"))
    }

    /// Get the profile directory for intermediate build artifacts built for the
    /// host architecture.
    #[instrument(name = "Workspace::host_profile_dir")]
    pub fn host_profile_dir(&self) -> AbsDirPath {
        self.build_dir()
            .try_join_dir(self.profile.as_str())
            .expect("profile should be valid directory name")
    }

    /// Get the profile directory for intermediate build artifacts built for the
    /// target architecture.
    ///
    /// When `--target` is set, this is different from the host profile
    /// directory, and library and build script execution artifacts are stored
    /// in the target profile directory.
    #[instrument(name = "Workspace::target_profile_dir")]
    pub fn target_profile_dir(&self) -> AbsDirPath {
        match &self.target_arch {
            Some(target_arch) => self
                .build_dir()
                .try_join_dirs(vec![target_arch.as_str(), self.profile.as_str()])
                .expect("target arch and profile should be valid directory names"),
            None => self.host_profile_dir(),
        }
    }

    // TODO: Rather than returning an `AbsDirPath`, maybe the `*_profile_dir`
    // methods should return a `ProfileDir` struct with `fingerprint_dir`,
    // `build_script_dir`, `deps_dir`, etc. methods? Would that simplify things?

    /// Get the build plan by running `cargo build --build-plan` with the
    /// provided arguments.
    #[instrument(name = "Workspace::build_plan")]
    async fn build_plan(
        &self,
        args: impl AsRef<CargoBuildArguments> + std::fmt::Debug,
    ) -> Result<BuildPlan> {
        let build_dir = self.build_dir();

        // Running `cargo build --build-plan` deletes a bunch of items in the `target`
        // directory. To work around this we temporarily move `target` -> run
        // the build plan -> move it back. If the rename fails (e.g., permissions,
        // cross-device), we proceed without it; this will then have the original issue
        // but at least won't break the build.
        let temp = self
            .root
            .try_join_dir(format!("target.backup.{}", Uuid::new_v4()))?;

        let renamed = fs::rename(&build_dir, &temp).await.is_ok();

        defer! {
            if renamed {
                let build_dir = build_dir.as_std_path();
                #[allow(clippy::disallowed_methods, reason = "cannot use async in defer")]
                let _ = std::fs::remove_dir_all(build_dir);
                #[allow(clippy::disallowed_methods, reason = "cannot use async in defer")]
                let _ = std::fs::rename(&temp.as_std_path(), build_dir);
            }
        }

        // From testing locally, it doesn't seem to matter in which order we
        // pass the flags but we pass the user flags first just in case as that
        // seems like it'd follow the principle of least surprise if ordering
        // ever does matter.
        let mut build_args = args.as_ref().to_argv();
        build_args.extend([
            String::from("--build-plan"),
            String::from("-Z"),
            String::from("unstable-options"),
        ]);
        let output = cargo::invoke_output("build", build_args, [("RUSTC_BOOTSTRAP", "1")])
            .await
            .context("run cargo command")?;
        serde_json::from_slice::<BuildPlan>(&output.stdout)
            .context("parse build plan")
            .with_section(move || {
                String::from_utf8_lossy(&output.stdout)
                    .to_string()
                    .header("Stdout:")
            })
            .with_section(move || {
                String::from_utf8_lossy(&output.stderr)
                    .to_string()
                    .header("Stderr:")
            })
    }

    #[instrument(name = "Workspace::unit_plan")]
    pub async fn unit_plan(
        &self,
        // TODO: These should just use self.args.
        args: impl AsRef<CargoBuildArguments> + std::fmt::Debug,
    ) -> Result<Vec<UnitPlan>> {
        let rustc = RustcMetadata::from_argv(&self.root, &args)
            .await
            .context("parsing rustc metadata")?;
        trace!(?rustc, "rustc metadata");

        // Note that build plans as a feature are deprecated[^1]. If a stable
        // alternative comes along, we should migrate.
        //
        // An alternative is the `--unit-graph` flag, which is unstable but not
        // deprecated[^2]. Unfortunately, unit graphs do not provide information
        // about the `rustc` invocation argv or the unit hash of the build
        // script execution, both of which are necessary to construct the
        // artifact cache key. We could theoretically reconstruct this
        // information using the JSON build messages and RUSTC_WRAPPER
        // invocation recording, but that's way more work for no stronger of a
        // stability guarantee.
        //
        // [^1]: https://github.com/rust-lang/cargo/issues/7614
        // [^2]: https://doc.rust-lang.org/cargo/reference/unstable.html#unit-graph
        let build_plan = self.build_plan(&args).await?;
        trace!(?build_plan, "build plan");

        let mut units: Vec<UnitPlan> = Vec::new();
        for mut invocation in build_plan.invocations {
            trace!(?invocation, "build plan invocation");

            // Skip first-party workspace members. We only cache third-party
            // dependencies. `CARGO_PRIMARY_PACKAGE` is set if the user
            // specifically requested the item to be built[^1]; while it's
            // technically possible for the user to do so for a third-party
            // dependency that's relatively rare (and arguably if they're asking
            // to compile it specifically, it _should_ probably be exempt from
            // cache).
            //
            // [^1]: https://doc.rust-lang.org/cargo/reference/environment-variables.html#:~:text=CARGO_PRIMARY_PACKAGE
            if let Some(v) = invocation.env.get("CARGO_PRIMARY_PACKAGE")
                && v == "1"
            {
                trace!("skipping: first party workspace member");
                continue;
            }

            // Figure out what kind of unit this invocation is.
            let package_name = invocation.package_name;
            let target_arch = invocation.target_arch;
            let deps = invocation.deps.into_iter().map(|d| d as u32).collect();
            let unit = if invocation.target_kind == [TargetKind::CustomBuild] {
                match invocation.compile_mode {
                    CargoCompileMode::Build => {
                        let compiled_program = invocation
                            .outputs
                            .into_iter()
                            // Filter out DWARF debugging files, which Cargo removes
                            // anyway.
                            .filter(|o| !o.ends_with(".dwp"))
                            .map(|o| AbsFilePath::try_from(o))
                            .exactly_one()
                            .unwrap_or_else(|_| {
                                bail!("build script compilation should produce exactly one output");
                            })?;
                        // Resolve `links`. We can just take the keys because we
                        // know they point to valid target files, and there's
                        // only one target file (the compiled program) that we
                        // care about anyway.
                        let linked_program = invocation
                            .links
                            .keys()
                            .into_iter()
                            .filter(|l| !l.ends_with(".dwp"))
                            .map(|l| AbsFilePath::try_from(l))
                            .exactly_one()
                            .unwrap_or_else(|_| {
                                bail!("build script compilation should produce exactly one output");
                            })?;
                        // Parse unit hash from file name of
                        // `build_script_{entrypoint_module_name}-{hash}`.
                        //
                        // We could also parse this from `-C extra-filename`.
                        let unit_hash = compiled_program
                            .file_name_str_lossy()
                            .ok_or_eyre("program file has no name")?
                            .rsplit_once('-')
                            .ok_or_eyre("program file has no unit hash")?
                            .1
                            .to_string();
                        let crate_name = invocation
                            .args
                            .crate_name()
                            .ok_or_eyre("build script compilation should have a crate name")?
                            .to_string();
                        let src_path = invocation.args.src_path().pipe(AbsFilePath::try_from)?;
                        UnitPlan {
                            unit_hash,
                            package_name,
                            crate_name,
                            target_arch,
                            deps,
                            mode: UnitPlanMode::BuildScriptCompilation(
                                BuildScriptCompilationUnitPlan {
                                    src_path,
                                    program: compiled_program,
                                    linked_program,
                                },
                            ),
                        }
                    }
                    CargoCompileMode::RunCustomBuild => {
                        let program = invocation.program.pipe(AbsFilePath::try_from)?;
                        let out_dir = invocation
                            .env
                            .remove("OUT_DIR")
                            .ok_or_eyre("build script execution should set OUT_DIR")?
                            .pipe(AbsDirPath::try_from)?;
                        let unit_dir = out_dir.parent().ok_or_eyre("OUT_DIR should have parent")?;
                        let unit_hash = unit_dir
                            .file_name_str_lossy()
                            .ok_or_eyre("build script execution directory should have name")?
                            .rsplit_once('-')
                            .ok_or_eyre("build script execution directory should have unit hash")?
                            .1
                            .to_string();
                        // Cargo defines the "crate name" of build script
                        // execution as the crate name of the build script being
                        // executed, which we infer from the name of the
                        // compiled program.
                        let crate_name = program
                            .file_name_str_lossy()
                            .ok_or_eyre("build script program should have name")?
                            .to_string()
                            // This is from Cargo's normalization logic.[^1]
                            //
                            // [^1]: https://github.com/attunehq/cargo/blob/7a93b36f1ae2f524d93efd16cd42864675f3e15b/src/cargo/core/manifest.rs#L961
                            .replace("-", "_");
                        UnitPlan {
                            unit_hash,
                            package_name,
                            crate_name,
                            target_arch,
                            deps,
                            mode: UnitPlanMode::BuildScriptExecution(
                                BuildScriptExecutionUnitPlan { program, out_dir },
                            ),
                        }
                    }
                    _ => bail!(
                        "unknown compile mode for build script: {:?}",
                        invocation.compile_mode
                    ),
                }
            } else if invocation.target_kind == [TargetKind::Bin] {
                // Binaries are _always_ first-party code. Do nothing for now.
                continue;
            } else if invocation.target_kind.contains(&TargetKind::Lib)
                || invocation.target_kind.contains(&TargetKind::RLib)
                || invocation.target_kind.contains(&TargetKind::CDyLib)
                || invocation.target_kind.contains(&TargetKind::ProcMacro)
            {
                // Sanity check: everything here should be a dependency being
                // compiled.
                if invocation.compile_mode != CargoCompileMode::Build {
                    bail!(
                        "unknown compile mode for dependency: {:?}",
                        invocation.compile_mode
                    );
                }

                // Filter out DWARF debugging files, which Cargo removes anyway.
                // These are created for proc macros and cdylibs on Linux (they
                // are `.so.dwp` files).
                //
                // Note there is no need to resolve `links` for library crates.
                // They are never linked unless they are first-party, and we are
                // skipping first-party crates for now anyway.
                let outputs = invocation
                    .outputs
                    .into_iter()
                    .filter(|o| !o.ends_with(".dwp"))
                    .map(|o| AbsFilePath::try_from(o))
                    .collect::<Result<Vec<_>>>()?;
                let crate_name = invocation
                    .args
                    .crate_name()
                    .ok_or_eyre("no crate name")?
                    .to_owned();
                let src_path = invocation.args.src_path().pipe(AbsFilePath::try_from)?;
                // We could also parse this from `-C extra-filename`.
                let unit_hash = {
                    let compiled_file = outputs.first().ok_or_eyre("no compiled files")?;
                    let filename = compiled_file
                        .file_name()
                        .ok_or_eyre("no filename")?
                        .to_string_lossy();
                    let filename = filename.split_once('.').ok_or_eyre("no extension")?.0;

                    filename
                        .rsplit_once('-')
                        .ok_or_eyre(format!(
                            "no unit hash suffix in filename: {filename} (all files: {outputs:?})"
                        ))?
                        .1
                        .to_string()
                };

                UnitPlan {
                    unit_hash,
                    package_name,
                    crate_name,
                    target_arch,
                    deps,
                    mode: UnitPlanMode::LibraryCrate(LibraryCrateUnitPlan { src_path, outputs }),
                }
            } else {
                bail!("unsupported target kind: {:?}", invocation.target_kind);
            };
            units.push(unit);
        }

        Ok(units)
    }
}

#[derive(Debug, Clone, Eq, PartialEq, Hash, Serialize, Deserialize)]
pub struct UnitPlan {
    /// The directory hash of the unit, which is used to construct the unit's
    /// file directories.
    ///
    /// See the `*_dir` methods on `CompilationFiles`[^1] for details.
    ///
    /// [^1]: https://github.com/attunehq/cargo/blob/7a93b36f1ae2f524d93efd16cd42864675f3e15b/src/cargo/core/compiler/build_runner/compilation_files.rs#L117
    pub unit_hash: String,

    /// The package name of this unit.
    ///
    /// This is used to reconstruct expected output directories. See the `*_dir`
    /// methods on `CompilationFiles`[^1] for details.
    ///
    /// [^1]: https://github.com/attunehq/cargo/blob/7a93b36f1ae2f524d93efd16cd42864675f3e15b/src/cargo/core/compiler/build_runner/compilation_files.rs#L117
    pub package_name: String,

    /// The crate name of this unit.
    ///
    /// Note that this is not necessarily the _extern_ crate name, which can be
    /// affected by directives like `replace` and `patch`, and that the crate
    /// name used in fingerprints is the extern crate name[^1], not the
    /// canonical crate name.
    ///
    /// [^1]: https://github.com/attunehq/cargo/blob/7a93b36f1ae2f524d93efd16cd42864675f3e15b/src/cargo/core/compiler/fingerprint/mod.rs#L1366
    // FIXME: To properly support `replace` and `patch` directives, we need to
    // also calculate an extern_crate_name for each edge in the dependency
    // graph. Note that this is a per-edge value, not a per-unit value. Perhaps
    // we can derive this from the unit graph?
    pub crate_name: String,

    // TODO: Add target architecture, which is needed to compute the unit's
    // profile directory. Add it as an `Option<TargetArch>`, or similar. And maybe
    // add some helper `*_dir` methods?
    /// The unit's target architecture, if set.
    ///
    /// When None, this unit is not being compiled with a specific `--target` in
    /// mind, and therefore is being compiled for the host architecture.
    ///
    /// Note that some units (e.g. proc macros, build script compilations, and
    /// dependencies thereof) are compiled for the host architecture even when
    /// `--target` is set to a different architecture. This field already takes
    /// that into account.
    pub target_arch: Option<String>,

    /// The dependencies of this unit.
    ///
    /// This is parsed from the dependencies in the unit's build plan
    /// invocation. Note that units can depend on arbitrary other units. For
    /// example, build script executions can depend on other build script
    /// executions because of the `links` field[^1] or library crates if they
    /// use those libraries.
    ///
    /// This is used to rewrite the unit's fingerprint on restore by rewriting
    /// the fingerprints in the `deps` field.
    ///
    /// [^1]: https://doc.rust-lang.org/cargo/reference/build-scripts.html#the-links-manifest-key
    pub deps: Vec<u32>,

    /// Mode-specific information about this unit.
    ///
    /// This is similar to an amalgamation of TargetKind[^1] and
    /// CompileMode[^2].
    ///
    /// Note that we separate compiling library crates from build scripts
    /// because they store artifacts at different paths in the build directory.
    ///
    /// [^1]: https://github.com/attunehq/cargo/blob/7a93b36f1ae2f524d93efd16cd42864675f3e15b/src/cargo/core/manifest.rs#L215
    /// [^2]: https://github.com/attunehq/cargo/blob/7a93b36f1ae2f524d93efd16cd42864675f3e15b/src/cargo/core/compiler/build_config.rs#L171
    pub mode: UnitPlanMode,
}

#[derive(Debug, Clone, Eq, PartialEq, Hash, Serialize, Deserialize)]
pub enum UnitPlanMode {
    LibraryCrate(LibraryCrateUnitPlan),
    BuildScriptCompilation(BuildScriptCompilationUnitPlan),
    BuildScriptExecution(BuildScriptExecutionUnitPlan),
}

#[derive(Debug, Clone, Eq, PartialEq, Hash, Serialize, Deserialize)]
pub struct LibraryCrateUnitPlan {
    pub src_path: AbsFilePath,
    pub outputs: Vec<AbsFilePath>,
}

#[derive(Debug, Clone, Eq, PartialEq, Hash, Serialize, Deserialize)]
pub struct BuildScriptCompilationUnitPlan {
    /// The path to the build script's main entrypoint source file. This is
    /// usually `build.rs` within the package's source code, but can vary if
    /// the package author sets `package.build` in the package's
    /// `Cargo.toml`, which changes the build script's name[^1].
    ///
    /// This is parsed from the rustc invocation arguments in the unit's
    /// build plan invocation.
    ///
    /// This is used to rewrite the build script compilation's fingerprint
    /// on restore.
    ///
    /// [^1]: https://doc.rust-lang.org/cargo/reference/manifest.html#the-build-field
    pub src_path: AbsFilePath,

    /// Build scripts always compile to a single program and a renamed hard
    /// link to the same program.
    ///
    /// This is parsed from the `outputs` and `links` paths in the unit's
    /// build plan invocation.
    ///
    /// These file paths must have their mtimes modified to be later than
    /// the fingerprint's invoked timestamp for the unit to be marked fresh.
    // TODO: We could simplify this struct. You can actually derive both of
    // these paths from the build script entrypoint module name and the unit
    // hash, and you can derive the build script entrypoint module name from the
    // src_path. So really, the only field we _need_ is `src_path`.
    //
    // TODO: Add impls on these unit plan structs to construct relevant paths?
    pub program: AbsFilePath,
    pub linked_program: AbsFilePath,
}

#[derive(Debug, Clone, Eq, PartialEq, Hash, Serialize, Deserialize)]
pub struct BuildScriptExecutionUnitPlan {
    // Note that we don't save src_path for build script execution because this
    // field is always set to `""` in the fingerprint for build script execution
    // units[^1].
    //
    // [^1]: https://github.com/attunehq/cargo/blob/7a93b36f1ae2f524d93efd16cd42864675f3e15b/src/cargo/core/compiler/fingerprint/mod.rs#L1665

    /// The compiled build script program being executed.
    pub program: AbsFilePath,
    /// The OUT_DIR where user-defined build script output files should be
    /// written.
    ///
    /// This is parsed from the environment variables in the unit's
    /// execution.
    ///
    /// This folder must have its mtime modified to be later than the
    /// fingerprint's invoked timestamp for the unit to be marked fresh.
    // TODO: We don't actually need this field given that we've already parsed
    // the unit hash out, right? Because we can reconstruct this path.
    pub out_dir: AbsDirPath,
}

#[cfg(test)]
mod tests {
    use super::*;
    use pretty_assertions::assert_eq as pretty_assert_eq;

    #[tokio::test]
    async fn build_plan_flag_order_does_not_matter() {
        // This is a relatively basic test to start with; if we find other edge
        // cases we want to test we should add them here (or in a similar test).
        let user_args = ["--release"];
        let tool_args = ["--build-plan", "-Z", "unstable-options"];
        let env = [("RUSTC_BOOTSTRAP", "1")];
        let cmd = "build";

        let args = user_args.iter().chain(tool_args.iter());
        let user_args_first = match cargo::invoke_output(cmd, args, env).await {
            Ok(output) => output.stdout,
            Err(e) => panic!("user args first should succeed: {e}"),
        };

        let args = tool_args.iter().chain(user_args.iter());
        let tool_args_first = match cargo::invoke_output(cmd, args, env).await {
            Ok(output) => output.stdout,
            Err(e) => panic!("tool args first should succeed: {e}"),
        };

        let user_plan = serde_json::from_slice::<BuildPlan>(&user_args_first).unwrap();
        let tool_plan = serde_json::from_slice::<BuildPlan>(&tool_args_first).unwrap();
        pretty_assert_eq!(
            user_plan,
            tool_plan,
            "both orderings should produce same build plan"
        );
    }
}
